### ISSUE TITLE
PC Opera

### ISSUE THREAD

**Issue by jessicali673** [lilbaj/web-design-2-independent-project#6]
Your website is so amazing!! Love your animations and colour gradient
Looking great on Opera for PC!
The only thing not working is your video for motion
![image](https://user-images.githubusercontent.com/55094160/101945060-a8b09500-3bbb-11eb-8ef0-2fdb03b7e94d.png)

Amazing work!

**Comment by lilbaj** [comment]
Thank you so much! im gonna make sure the video is properly link since i had a few issues with that earlier. Thanks again!!
